name: podcast
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  agora_rtc_engine: ^6.3.0
  bloc: ^8.1.1
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  get_it: ^7.7.0
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  hydrated_bloc: ^9.1.5
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - mock/
