name: podcast
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  agora_rtc_engine: ^6.3.0
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
